name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy env file
        run: |
          echo '${{ secrets.ENV }}' > .env

      - name: Copy project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "./backend.Dockerfile, ./prisma-migrate.Dockerfile, ./prisma.Dockerfile, ./docker-compose.yml, ./src, ./migrations, ./requirements.txt, ./schema.prisma, .env"
          target: "/home/ec2-user/vulgatech-postman"

      - name: Run docker-compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/vulgatech-postman
            sudo docker-compose down || true
            sudo docker-compose up --build -d
